Student student = new Student("CIST", "1234");
student.firstName = "Eric";
student.lastName = "Lahti";
student.FavoriteBook = "Fear And Loathing in Las Vegas";
student.Score(1, 100);
student.Score(2, 98);
student.Score(3, 100);
student.DropClass();
Console.WriteLine(student.firstName + " " + student.lastName);
Console.WriteLine(student.major + " " + student.ID);
Console.WriteLine("Scores: " + student.GetScores());
Student cappy = new Student("DogStuff", "1");
cappy.firstName = "Cappy";
cappy.lastName = "Lahti";
cappy.Score(1, 100);
cappy.Score(2, 100);
cappy.Score(3, 100);
Console.WriteLine(cappy.firstName + " " + cappy.lastName);
Console.WriteLine(cappy.major + " " + cappy.ID);
